# Generated by Django 4.2 on 2025-04-15 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(help_text='E.g., +254123456789', max_length=15, unique=True)),
                ('pin', models.CharField(help_text='4-digit PIN, e.g., 1234', max_length=4)),
                ('celo_address', models.CharField(help_text='Mock Celo address', max_length=42, unique=True)),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, help_text='cUSD balance', max_digits=10)),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tx_hash', models.CharField(help_text='Mock tx hash', max_length=66)),
                ('amount', models.DecimalField(decimal_places=2, help_text='cUSD amount', max_digits=10)),
                ('type', models.CharField(choices=[('deposit', 'Deposit'), ('withdraw', 'Withdraw')], max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='core.user')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
            },
        ),
    ]
